spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delivery
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  datasource-ps:
    url: jdbc:postgresql://localhost:5432/delivery
    username: root
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

postgre-db:
  query:
    delivery: select * from delivery where created_at between '{lastRunDateTime}' and '{current_date}';

mysql-db:
  query:
    dataInsertion: INSERT IGNORE INTO msdelivery(id,client_id,delivery_company,received_delivery,created_at)
                   VALUES (?,?,?,?,?)
    SQL_INSERT_LAST_RUN: INSERT INTO last_record(record_date_time) VALUES(?)
    SQL_RETRIEVE_LAST_RUN: SELECT record_date_time FROM last_record ORDER BY record_date_time DESC LIMIT 1
    SQL_UPDATE_LAST_RUN: UPDATE last_record SET record_date_time = '{lastRunDateTime}' where id=1;



