spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delivery
    username: root
    password: ostentatious
    driver-class-name: com.mysql.cj.jdbc.Driver

  datasource-ps:
    url: jdbc:postgresql://localhost:5432/delivery
    username: root
    password: ostentatious
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
